include changes to deploy 1.35 with ubuntu 24 and etcd backups

diff --git a/templates/capi-cluster-install.sh.j2 b/templates/capi-cluster-install.sh.j2
--- a/templates/capi-cluster-install.sh.j2
+++ b/templates/capi-cluster-install.sh.j2
@@ -23,6 +23,9 @@ LOG_FILE="/var/log/capi-mgmt-cluster-install.log"
 # declare the kubeconfig file
 KUBECONFIG_FILE="$HOME/.kube/config"
 
+# declare the backup directory
+ETCD_BACKUP_DIR="/var/backups"
+
 # send xtrace output to FD 3, which is appended to the log file
 exec 3>>"$LOG_FILE"
 export BASH_XTRACEFD=3
@@ -35,6 +38,9 @@ echo > "$LOG_FILE"
 
 # enable command tracing
 set -x
+
+# enable generic error handler
+#trap 'echo "ERROR: Script failed; check log file for further details" >&2' ERR
 
 function install_k8s_cluster () {
 
@@ -63,7 +69,7 @@ fi
 pushd "$KUBESPRAY_REPO_DIR" &>> "$LOG_FILE"
 
 # checkout the repo to tag v2.30.0
-git checkout tags/v2.30.0 &>> "$LOG_FILE"
+#git checkout tags/v2.30.0 &>> "$LOG_FILE"
 
 # install the required pip packages for kubespray
 "$KUBESPRAY_VENV_DIR/bin/python" -m pip install --upgrade pip &>> "$LOG_FILE"
@@ -226,6 +232,84 @@ if ! kubectl get providers -A &>> "$LOG_FILE"; then
 fi
 }
 
+function config_etcd_backup_disk () {
+
+  # check if the etcd backup dir is already mounted
+  if [ $(mount | grep $ETCD_BACKUP_DIR | wc -l) -gt 0 ]; then
+    echo "$ETCD_BACKUP_DIR is already mounted; no further actions required" &>> "$LOG_FILE"
+    return 0
+  fi
+
+  # declare the array for unused disks
+  unused_disks=()
+
+  # obtain the unused disk on the node
+  for disk in $(lsblk -dn -o NAME,TYPE | awk '$2=="disk"{print $1}'); do
+    
+    node_disk="/dev/$disk"
+
+    # skip if the disk is mounted
+    if lsblk -nr "$node_disk" -o MOUNTPOINT | grep -q .; then
+      continue
+    fi
+
+    # skip if there are partitions exist on the disk
+    if [ "$(lsblk -nr "$node_disk" -o NAME | wc -l)" -ne 1 ]; then
+      continue
+    fi
+
+    # skip if filesystem signature exists on the device
+    if blkid "$node_disk" > /dev/null 2>&1; then
+      continue
+    fi
+
+    # if the disk is unused; append it to the array
+    unused_disks+=("$node_disk")
+  done
+
+{% raw %}
+  # if there are no unused disks exit
+  if [ "${#unused_disks[@]}" -eq 0 ]; then
+    echo "Expected atleast one unused disk for etcd backup!" &>> "$LOG_FILE"
+    exit 1
+  fi
+{% endraw %}
+
+  echo "Found unused disk for etcd backup dir: ${unused_disks[0]}" &>> "$LOG_FILE"
+
+  etcd_backup_disk="${unused_disks[0]}"
+
+  # for the disk and mount it on the etcd backup dir
+  echo "Formatting the disk ${unused_disks[0]}" &>> "$LOG_FILE"
+  mkfs -t ext4 "$etcd_backup_disk" &>> "$LOG_FILE"
+
+  # create the mount point directory for etcd backup
+  mkdir -p "$ETCD_BACKUP_DIR"
+
+  # mount the etcd backup dir
+  mount "$etcd_backup_disk" "$ETCD_BACKUP_DIR"
+
+  UUID=$(blkid -s UUID -o value "$etcd_backup_disk")
+
+  echo "Persisting mount in /etc/fstab" &>> "$LOG_FILE"
+  grep -q "$UUID" /etc/fstab || echo "UUID=$UUID $ETCD_BACKUP_DIR ext4 defaults 0 2" >> /etc/fstab
+}
+
+function config_etcd_backup_cron () {
+
+  # declare local variables for etcd backup
+  local ETCD_CRON="0 */6 * * * /usr/local/bin/etcd-backup.sh"
+
+  if ! crontab -l 2>/dev/null | grep -F "$ETCD_CRON" >/dev/null; then
+    echo "ETCD backup cron already configured" &>> "$LOG_FILE"
+  else
+    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
+    echo "ETCD backup cron enabled" &>> "$LOG_FILE"
+  fi
+}
+
 install_k8s_cluster
 install_helm
 install_capi_components
+config_etcd_backup_disk
+config_etcd_backup_cron
